Repository openiddict/openiddict-documentation, pull requests merged in 2024-08, with the labels that each got.

#121 Enable clean URLs support
  .vitepress/config.mts
  guides/migration/20-to-30.md
Labels: enhancement

#122 Move the introduction page to the root folder
  .vitepress/config.mts
  guides/contributing-a-new-web-provider.md
  integrations/aspnet-core.md
  introduction.md
Labels: enhancement

#123 Use title badges
  configuration/authorization-storage.md
  configuration/proof-key-for-code-exchange.md
  configuration/token-storage.md
  integrations/aspnet-core.md
Labels: enhancement

#124 Document the System.Net.Http integration
  .vitepress/config.mts
  configuration/encryption-and-signing-credentials.md
  configuration/token-formats.md
  integrations/aspnet-core.md
  integrations/system-net-http.md
  integrations/web-providers.md
Labels: enhancement

#125 Fix the incorrect indentation used in the Quartz.NET documentation
  integrations/aspnet-core.md
  integrations/quartz.md
Labels: bug

#126 Fix a broken link in the ASP.NET Core integration documentation
  integrations/aspnet-core.md
Labels: bug

#127 Update the "choosing the right flow" guide to mention that all the flows are supported by the OpenIddict client, except response_type=token
  SECURITY.md
  configuration/application-permissions.md
  configuration/authorization-storage.md
  configuration/claim-destinations.md
  configuration/encryption-and-signing-credentials.md
  configuration/index.md
  configuration/proof-key-for-code-exchange.md
  configuration/token-formats.md
  configuration/token-storage.md
  guides/choosing-the-right-flow.md
  guides/contributing-a-new-web-provider.md
  guides/getting-started/creating-your-own-server-instance.md
  guides/getting-started/implementing-token-validation-in-your-apis.md
  guides/getting-started/integrating-with-a-remote-server-instance.md
  integrations/aspnet-core.md
  integrations/entity-framework-core.md
  integrations/entity-framework.md
  integrations/index.md
  integrations/mongodb.md
  integrations/quartz.md
  integrations/system-net-http.md
  integrations/web-providers.md
Labels: enhancement

#128 Move the ASP.NET Core Data Protection documentation to its own page
  .vitepress/config.mts
  .vitepress/theme/custom.css
  .vitepress/theme/index.ts
  configuration/proof-key-for-code-exchange.md
  configuration/token-formats.md
  configuration/token-storage.md
  guides/choosing-the-right-flow.md
  index.md
  integrations/aspnet-core-data-protection.md
  integrations/system-net-http.md
  introduction.md
Labels: enhancement

#129 Update the EF/EF Core/MongoDB links to point to the local documentation instead of the NuGet packages
  guides/getting-started/integrating-with-a-remote-server-instance.md
  introduction.md
Labels: enhancement

#130 Document the operating systems integration
  .vitepress/config.mts
  guides/getting-started/integrating-with-a-remote-server-instance.md
  integrations/aspnet-core.md
  integrations/operating-systems.md
  integrations/system-net-http.md
Labels: enhancement

#131 Clarify that Android, iOS, Mac Catalyst and macOS support will be available in OpenIddict 5.8
  integrations/operating-systems.md
Labels: enhancement

#132 Bump OpenIddict to 5.7.1
  guides/getting-started/creating-your-own-server-instance.md
  guides/getting-started/implementing-token-validation-in-your-apis.md
  guides/getting-started/integrating-with-a-remote-server-instance.md
  guides/migration/40-to-50.md
  integrations/aspnet-core.md
  integrations/entity-framework-core.md
  integrations/entity-framework.md
  integrations/mongodb.md
  integrations/operating-systems.md
  integrations/quartz.md
  integrations/system-net-http.md
  integrations/web-providers.md
Labels: dependencies

#133 Update system-net-http.md
  configuration/authorization-storage.md
  configuration/token-formats.md
  integrations/system-net-http.md
  introduction.md
Labels: enhancement

#135 Bump OpenIddict to 5.8.0
  guides/getting-started/creating-your-own-server-instance.md
  guides/getting-started/implementing-token-validation-in-your-apis.md
  guides/getting-started/integrating-with-a-remote-server-instance.md
  guides/migration/40-to-50.md
  integrations/aspnet-core.md
  integrations/entity-framework-core.md
  integrations/entity-framework.md
  integrations/mongodb.md
  integrations/operating-systems.md
  integrations/quartz.md
  integrations/system-net-http.md
  integrations/web-providers.md
Labels: dependencies

#136 Update the documentation to clarify mobile platforms are supported by the OpenIddict Web providers
  guides/getting-started/index.md
  integrations/web-providers.md
  introduction.md
Labels: enhancement

#137 Add an error controller example to the status code pages middleware documentation
  integrations/aspnet-core.md
Labels: enhancement
