Repository openiddict/openiddict-documentation, pull requests merged in 2024-07, with the labels that each got.

#107 Enable the search bar
  .vitepress/config.mts
Labels: enhancement

#108 Fix the link to the getting started index page
  .vitepress/config.mts
Labels: bug

#109 Update index.md - added RSK Saml
  integrations/index.md
Labels: enhancement, community contribution

#110 Add a Twitter link
  .vitepress/config.mts
Labels: enhancement

#112 Document the OpenIddict Web providers
  .vitepress/config.mts
  guides/contributing-a-new-web-provider.md
  guides/getting-started/integrating-with-a-remote-server-instance.md
  guides/migration/40-to-50.md
  integrations/web-providers.md
Labels: enhancement

#113 Disable the automatic previous/next links and fix a rendering issue affecting the Quartz documentation
  .vitepress/config.mts
  integrations/quartz.md
Labels: bug

#114 Add a link to the Web providers documentation
  guides/contributing-a-new-web-provider.md
  guides/getting-started/integrating-with-a-remote-server-instance.md
  integrations/web-providers.md
Labels: enhancement

#116 Add a documentation page dedicated to the ASP.NET Core integration
  .vitepress/config.mts
  guides/getting-started/creating-your-own-server-instance.md
  guides/getting-started/implementing-token-validation-in-your-apis.md
  index.md
  integrations/aspnet-core.md
  integrations/entity-framework.md
Labels: enhancement

#117 Simplify the home page
  index.md
Labels: enhancement

#118 Revamp the introduction page
  introduction/index.md
Labels: enhancement

#119 Document the authentication scheme forwarding feature
  integrations/aspnet-core.md
  introduction/index.md
Labels: enhancement

#120 Update the configuration documentation to cover the OpenIddict client
  configuration/application-permissions.md
  configuration/authorization-storage.md
  configuration/claim-destinations.md
  configuration/encryption-and-signing-credentials.md
  configuration/index.md
  configuration/proof-key-for-code-exchange.md
  configuration/token-formats.md
  configuration/token-storage.md
  integrations/aspnet-core.md
  integrations/index.md
Labels: enhancement
